version: "3.8"

services:
  get_work_ids:
    build: get_work_ids
    command: python get_work_ids.py --n=10 --query=horse
    volumes:
      - $PWD/data:/data
  get_pages:
    build: data_collection
    command: python get_pages.py --work-id=n43aqrgd
    volumes:
      - $PWD/data:/data
  ocr_images:
    build: data_collection
    command: python ocr_images.py --work-id-path="/data/work_ids.csv"
    volumes:
      - $PWD/data:/data
  train_autoencoder:
    build: train_autoencoder
    command: python train_autoencoder.py /data/pages
    volumes:
      - $PWD/data:/data
      - $HOME/.cache/torch/:/root/.cache/torch/
