version: "3.8"

services:
  get_work_ids:
    build: get_work_ids
    command: python get_work_ids.py --n=10 --query=horse
    volumes:
      - $HOME/repos/data-science/image_extraction/data:/data
  get_pages:
    build:
      context: data_collection
      dockerfile: get_pages.dockerfile
    command: python get_pages.py --work-id=n43aqrgd
    volumes:
      - $HOME/repos/data-science/image_extraction/data:/data
  ocr_images:
    build:
      context: data_collection
      dockerfile: ocr_images.dockerfile
    command: python ocr_images.py --work-id-path="/data/work_ids.csv"
    volumes:
      - $HOME/repos/data-science/image_extraction/data:/data

